<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>

<head>
    <title><?= $host ?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width">
    <style type="text/css">
    <?php include 'style.css'; ?>
    </style>
</head>

<body>

<?php if ($headers_only): ?>

    <p id="headers">
        <?php foreach($headers as $key => $value): ?>
            <span class="header-key"><?= $key ?></span>:
            <span class="header-value"><?= $value ?></span><br>
        <?php endforeach; ?>
    </p>

<?php elseif(IS_IP_REQUEST): ?>

    <p id="ip"><?= $remote_ip; ?></p>

    <?php if($remote_host != $remote_ip): ?>
        <p id="host"><?php echo $remote_host; ?></p>
    <?php endif; ?>

<?php elseif($host == HOST_UA): ?>

    <p id="ua"><?= $user_agent ?></p>

<?php endif; ?>

</body>

</html>
