<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>

<head>
    <title><?= $host ?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width">
    <style type="text/css">
    <?php include 'style.css'; ?>
    </style>
</head>

<body>

<?php if($host == 'ip.bwerp.net'): ?>

    <p id="ip"><?= $remote_ip; ?></p>

    <?php if($remote_host != $remote_ip): ?>
        <p id="host"><?php echo $remote_host; ?></p>
    <?php endif; ?>

<?php elseif($host == 'ua.bwerp.net'): ?>

    <p id="ua"><?= $user_agent ?></p>

<?php endif; ?>

</body>

</html>
